CREATE DATABASE management_test;

USE management_test;

CREATE TABLE EMPLOYEE
(
  Id INT AUTO_INCREMENT primary key,
  Name VARCHAR(50) NOT NULL,
  Role VARCHAR(10) NOT NULL,
  Gender VARCHAR(10) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Age INT NOT NULL
);

CREATE TABLE USER
(
  Id INT AUTO_INCREMENT primary key,
  Name VARCHAR(50) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  EmployeeId INT,
  FOREIGN KEY (EmployeeId) REFERENCES EMPLOYEE(Id)
);

CREATE TABLE CUSTOMER
(
  Id INT AUTO_INCREMENT primary key,
  Name VARCHAR(50) NOT NULL
);

CREATE TABLE COURSE
(
  Id INT AUTO_INCREMENT primary key,
  CoachId INT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  FOREIGN KEY (CoachId) REFERENCES EMPLOYEE(Id)
);

CREATE TABLE CUSTOMER_COURSE
(
  Id INT AUTO_INCREMENT primary key,
  CustomerId INT,
  CourseId INT,
  FOREIGN KEY (CustomerId) REFERENCES CUSTOMER(Id) ON DELETE CASCADE,
  FOREIGN KEY (CourseId) REFERENCES COURSE(Id) ON DELETE CASCADE
);

CREATE TABLE SCHEDULE
(
  Id INT AUTO_INCREMENT primary key,
  Time DATE NOT NUll,
  CourseId INT,
  PrivateCustomerId INT,
  FOREIGN KEY (CourseId) REFERENCES COURSE(Id) ON DELETE CASCADE,
  FOREIGN KEY (PrivateCustomerId) REFERENCES CUSTOMER(Id) ON DELETE CASCADE

--   CustomerCourseId INT,
--   FOREIGN KEY (CustomerCourseId) REFERENCES CUSTOMER_COURSE(Id) ON DELETE CASCADE
);